function(add_thread_sanitizer target)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=thread)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        message(WARNING "Thread Sanitizer is not supported on MSVC.")
    else()
        message(WARNING "Unknown compiler: Thread Sanitizer may not be supported.")
    endif()
endfunction()
